<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-IP80BGQ" failures="2" tests="9" name="RetryMultipleFailedTestCases" time="0.129" errors="0" timestamp="2022-03-19T15:29:10 IST">
  <testcase classname="mytests.MyTests" name="Test1" time="0.01">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test1(MyTests.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.004">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.005">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test2(MyTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test3" time="0.004"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
